
// contains all fonts used in themes once, even if used in more than one theme. 
// NOTE: this list can be used for the mpdf font config file.

  "roboto" => array(
    "R" => "Roboto-Regular.ttf",
    "B" => "Roboto-Bold.ttf",
    "I" => "Roboto-Italic.ttf",
    "BI" => "Roboto-BoldItalic.ttf",
  ),
  "texgyrecursor" => array(
    "R" => "TeXGyreCursor-Regular.ttf",
    "B" => "TeXGyreCursor-Bold.ttf",
    "I" => "TeXGyreCursor-Italic.ttf",
    "BI" => "TeXGyreCursor-BoldItalic.ttf",
  ),
  "roboto-condensed" => array(
    "R" => "RobotoCondensed-Regular.ttf",
    "B" => "RobotoCondensed-Bold.ttf",
    "I" => "RobotoCondensed-Italic.ttf",
    "BI" => "RobotoCondensed-BoldItalic.ttf",
  ),
  "freemono" => array(
    "R" => "FreeMono.ttf",
    "B" => "FreeMonoBold.ttf",
    "I" => "FreeMonoOblique.ttf",
    "BI" => "FreeMonoBoldOblique.ttf",
  ),
  "dejavusans" => array(
    "R" => "DejaVuSans.ttf",
    "B" => "DejaVuSans-Bold.ttf",
    "I" => "DejaVuSans-Oblique.ttf",
    "BI" => "DejaVuSans-BoldOblique.ttf",
  ),
  "ubuntu-mono" => array(
    "R" => "UbuntuMono-R.ttf",
    "B" => "UbuntuMono-B.ttf",
    "I" => "UbuntuMono-RI.ttf",
    "BI" => "UbuntuMono-BI.ttf",
  ),
  "roboto-light" => array(
    "R" => "Roboto-Light.ttf",
    "B" => "Roboto-Regular.ttf",
    "I" => "Roboto-LightItalic.ttf",
    "BI" => "Roboto-Italic.ttf",
  ),
  "texgyreadventor" => array(
    "R" => "TeXGyreAdventor-Regular.ttf",
    "B" => "TeXGyreAdventor-Bold.ttf",
    "I" => "TeXGyreAdventor-Italic.ttf",
    "BI" => "TeXGyreAdventor-BoldItalic.ttf",
  ),
  "sourcesanspro" => array(
    "R" => "SourceSansPro-Regular.ttf",
    "B" => "SourceSansPro-Bold.ttf",
    "I" => "SourceSansPro-Italic.ttf",
    "BI" => "SourceSansPro-BoldItalic.ttf",
  ),
  "ubuntu" => array(
    "R" => "Ubuntu-R.ttf",
    "B" => "Ubuntu-B.ttf",
    "I" => "Ubuntu-RI.ttf",
    "BI" => "Ubuntu-BI.ttf",
  ),
  "merriweatherserif" => array(
    "R" => "Merriweatherserif300.ttf",
    "B" => "Merriweatherserif700.ttf",
    "I" => "Merriweatherserif300italic.ttf",
    "BI" => "Merriweatherserif700italic.ttf",
  ),
  "lato" => array(
    "R" => "Lato-Regular.ttf",
    "B" => "Lato-Bold.ttf",
    "I" => "Lato-Italic.ttf",
    "BI" => "Lato-BoldItalic.ttf",
  ),
  "crimsontext" => array(
    "R" => "CrimsonTextregular.ttf",
    "B" => "CrimsonText700.ttf",
    "I" => "CrimsonTextitalic.ttf",
    "BI" => "CrimsonText700italic.ttf",
  ),
  "istok" => array(
    "R" => "IstokWebregular.ttf",
    "B" => "IstokWeb700.ttf",
    "I" => "IstokWebitalic.ttf",
    "BI" => "IstokWeb700italic.ttf",
  ),
  "alegreyaserif" => array(
    "R" => "Alegreyaregular.ttf",
    "B" => "Alegreya700.ttf",
    "I" => "Alegreyaitalic.ttf",
    "BI" => "Alegreya700italic.ttf",
  ),
  "alegreyasans" => array(
    "R" => "AlegreyaSansregular.ttf",
    "B" => "AlegreyaSans700.ttf",
    "I" => "AlegreyaSansitalic.ttf",
    "BI" => "AlegreyaSans700italic.ttf",
  ),
  "vollkorn" => array(
    "R" => "Vollkornregular.ttf",
    "B" => "Vollkorn700.ttf",
    "I" => "Vollkornitalic.ttf",
    "BI" => "Vollkorn700italic.ttf",
  ),
  "cabin" => array(
    "R" => "Cabin700.ttf",
    "B" => "Cabin700.ttf",
    "I" => "Cabin700.ttf",
    "BI" => "Cabin700.ttf",
  ),
  "merriweathersanstext" => array(
    "R" => "MerriweatherSans300.ttf",
    "B" => "MerriweatherSans700.ttf",
    "I" => "MerriweatherSans300italic.ttf",
    "BI" => "MerriweatherSans700italic.ttf",
  ),
  "merriweathersanshead" => array(
    "R" => "MerriweatherSans700.ttf",
    "B" => "MerriweatherSans800.ttf",
    "I" => "MerriweatherSans700italic.ttf",
    "BI" => "MerriweatherSans800italic.ttf",
  ),
  "lora" => array(
    "R" => "Loraregular.ttf",
    "B" => "Lora700.ttf",
    "I" => "Loraitalic.ttf",
    "BI" => "Lora700italic.ttf",
  ),
  "montserrat" => array(
    "R" => "Montserratregular.ttf",
    "B" => "Montserrat700.ttf",
    "I" => "Montserratregular.ttf",
    "BI" => "Montserrat700.ttf",
  ),
  "ubuntu-light" => array(
    "R" => "Ubuntu-L.ttf",
    "B" => "Ubuntu-M.ttf",
    "I" => "Ubuntu-LI.ttf",
    "BI" => "Ubuntu-MI.ttf",
  ),
  "texgyrepagella" => array(
    "R" => "TeXGyrePagella-Regular.ttf",
    "B" => "TeXGyrePagella-Bold.ttf",
    "I" => "TeXGyrePagella-Italic.ttf",
    "BI" => "TeXGyrePagella-BoldItalic.ttf",
  ),
  "im_fell_dw_pica_pro" => array(
    "R" => "IM_FELL_DW_Pica_PRO_Roman.ttf",
    "I" => "IM_FELL_DW_Pica_PRO_Italic.ttf",
  ),
  "texgyreschola" => array(
    "R" => "TeXGyreSchola-Regular.ttf",
    "B" => "TeXGyreSchola-Bold.ttf",
    "I" => "TeXGyreSchola-Italic.ttf",
    "BI" => "TeXGyreSchola-BoldItalic.ttf",
  ),